package store

import (
	"database/sql"
	"strings"
	"time"
)

type VirtualFolder struct {
	ID               int64      `json:"id"`
	Name             string     `json:"name"`
	Description      string     `json:"description"`
	AutoGenerated    bool       `json:"auto_generated"`
	Materialized     bool       `json:"materialized"`
	MaterializedPath *string    `json:"materialized_path"`
	CreatedAt        time.Time  `json:"created_at"`
}

type VirtualFolderDetail struct {
	VirtualFolder
	Files []File `json:"files"`
	Notes []Note `json:"notes"`
}

func (s *Store) ListVirtualFolders() ([]VirtualFolder, error) {
	rows, err := s.db.Query(`SELECT id, name, description, auto_generated, materialized, materialized_path, created_at FROM virtual_folders ORDER BY created_at DESC`)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var folders []VirtualFolder
	for rows.Next() {
		var f VirtualFolder
		if err := rows.Scan(&f.ID, &f.Name, &f.Description, &f.AutoGenerated, &f.Materialized, &f.MaterializedPath, &f.CreatedAt); err != nil {
			return nil, err
		}
		folders = append(folders, f)
	}
	return folders, rows.Err()
}

func (s *Store) GetVirtualFolder(id int64) (*VirtualFolder, error) {
	var f VirtualFolder
	err := s.db.QueryRow(`SELECT id, name, description, auto_generated, materialized, materialized_path, created_at FROM virtual_folders WHERE id = ?`, id).
		Scan(&f.ID, &f.Name, &f.Description, &f.AutoGenerated, &f.Materialized, &f.MaterializedPath, &f.CreatedAt)
	if err == sql.ErrNoRows {
		return nil, nil
	}
	return &f, err
}

func (s *Store) CreateVirtualFolder(name, description string, autoGenerated bool) (*VirtualFolder, error) {
	result, err := s.db.Exec(`INSERT INTO virtual_folders (name, description, auto_generated) VALUES (?, ?, ?)`, name, description, autoGenerated)
	if err != nil {
		return nil, err
	}
	id, _ := result.LastInsertId()
	return s.GetVirtualFolder(id)
}

func (s *Store) UpdateVirtualFolder(id int64, name *string, description *string) (*VirtualFolder, error) {
	if name != nil {
		s.db.Exec(`UPDATE virtual_folders SET name = ? WHERE id = ?`, *name, id)
	}
	if description != nil {
		s.db.Exec(`UPDATE virtual_folders SET description = ? WHERE id = ?`, *description, id)
	}
	return s.GetVirtualFolder(id)
}

func (s *Store) DeleteVirtualFolder(id int64) error {
	_, err := s.db.Exec(`DELETE FROM virtual_folders WHERE id = ?`, id)
	return err
}

func (s *Store) AddFileToFolder(folderID, fileID int64, source string) error {
	_, err := s.db.Exec(`INSERT OR IGNORE INTO virtual_folder_files (virtual_folder_id, file_id, source) VALUES (?, ?, ?)`, folderID, fileID, source)
	return err
}

func (s *Store) AddFilesToFolder(folderID int64, fileIDs []int64, source string) error {
	tx, err := s.db.Begin()
	if err != nil {
		return err
	}
	defer tx.Rollback()

	stmt, err := tx.Prepare(`INSERT OR IGNORE INTO virtual_folder_files (virtual_folder_id, file_id, source) VALUES (?, ?, ?)`)
	if err != nil {
		return err
	}
	defer stmt.Close()

	for _, fileID := range fileIDs {
		if _, err := stmt.Exec(folderID, fileID, source); err != nil {
			return err
		}
	}
	return tx.Commit()
}

func (s *Store) RemoveFileFromFolder(folderID, fileID int64) error {
	_, err := s.db.Exec(`DELETE FROM virtual_folder_files WHERE virtual_folder_id = ? AND file_id = ?`, folderID, fileID)
	return err
}

func (s *Store) ListFolderFiles(folderID int64) ([]File, error) {
	rows, err := s.db.Query(
		`SELECT f.id, f.path, f.name, f.extension, f.mime_type, f.size, f.parent_dir, f.status, f.modified_at, f.indexed_at, f.content_indexed_at
		 FROM files f JOIN virtual_folder_files vff ON f.id = vff.file_id WHERE vff.virtual_folder_id = ? ORDER BY f.name`,
		folderID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var files []File
	for rows.Next() {
		var f File
		if err := rows.Scan(&f.ID, &f.Path, &f.Name, &f.Extension, &f.MimeType, &f.Size, &f.ParentDir, &f.Status, &f.ModifiedAt, &f.IndexedAt, &f.ContentIndexedAt); err != nil {
			return nil, err
		}
		files = append(files, f)
	}
	return files, rows.Err()
}

func (s *Store) SetMaterialized(folderID int64, path string) error {
	_, err := s.db.Exec(`UPDATE virtual_folders SET materialized = 1, materialized_path = ? WHERE id = ?`, path, folderID)
	return err
}

func (s *Store) GetVirtualFolderDetail(id int64) (*VirtualFolderDetail, error) {
	folder, err := s.GetVirtualFolder(id)
	if err != nil || folder == nil {
		return nil, err
	}

	files, err := s.ListFolderFiles(id)
	if err != nil {
		return nil, err
	}

	notes, err := s.ListFolderNotes(id)
	if err != nil {
		return nil, err
	}

	return &VirtualFolderDetail{
		VirtualFolder: *folder,
		Files:         files,
		Notes:         notes,
	}, nil
}

func joinConditions(conditions []string, sep string) string {
	return strings.Join(conditions, sep)
}
